version: "3.9"
services:
  imagine_auth_db:
    image: postgres
    volumes:
      - ./tmp/postgresql/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: arqui
      POSTGRES_USER: arqui
      POSTGRES_DB: imagine_auth_db
  imagine_auth_ms:
    image: imagine_auth_ms
    command: bash -c "rm -f tmp/pids/server.pid && ls && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - imagine_auth_db